import { StyleSheet } from 'react-native';

import { createStyles } from 'shared/theme/createStyles';

export const useStyles = createStyles(
  ({ theme, scale, bottomInset = 0 }: any) => ({
    ...StyleSheet.create({
      flex: { flex: 1 },
      screen: {
        flex: 1,
        backgroundColor: theme.palette.background,
      },
      page: {
        flex: 1,
        minHeight: 0,
        backgroundColor: theme.palette.background,
      },
      contact: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(10),
      },
      contactPressed: { opacity: 0.72 },
      contactArrow: {
        color: theme.palette.neutral500,
        fontSize: scale(24),
        lineHeight: scale(28),
      },
      contactDetails: {
        flex: 1,
        gap: scale(2),
      },
      avatar: {
        width: scale(38),
        height: scale(38),
        borderRadius: scale(999),
        backgroundColor: theme.palette.violet300,
        alignItems: 'center',
        justifyContent: 'center',
        overflow: 'hidden',
      },
      avatarImage: { width: '100%', height: '100%' },
      avatarText: { fontWeight: '800', color: theme.palette.violet800 },
      name: {
        fontSize: scale(16),
        fontWeight: '800',
        color: theme.palette.text,
      },
      topic: {
        fontSize: scale(11),
        color: theme.palette.accent700,
      },
      messagesList: {
        flex: 1,
        minHeight: 0,
      },
      messages: {
        flexGrow: 1,
        gap: scale(8),
        paddingHorizontal: scale(18),
        paddingTop: scale(12),
      },
      overlay: {
        position: 'absolute',
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: theme.palette.background,
      },
      emptyMessages: { justifyContent: 'center' },
      emptyMessagesText: {
        paddingHorizontal: scale(28),
        color: theme.palette.neutral600,
        fontSize: scale(14),
        lineHeight: scale(21),
        textAlign: 'center',
      },
      centeredState: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        gap: scale(14),
        paddingHorizontal: scale(24),
      },
      stateText: {
        color: theme.palette.neutral600,
        fontSize: scale(14),
        textAlign: 'center',
      },
      missingState: {
        flex: 1,
        justifyContent: 'center',
        paddingHorizontal: scale(26),
        paddingBottom: scale(40) + bottomInset,
      },
      initialError: {
        flex: 1,
        justifyContent: 'center',
        paddingHorizontal: scale(26),
      },
      historyState: {
        minHeight: scale(42),
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: scale(8),
        marginBottom: scale(4),
      },
      historyText: {
        color: theme.palette.neutral600,
        fontSize: scale(12),
      },
      historyError: {
        alignItems: 'center',
        gap: scale(4),
        paddingVertical: scale(9),
        marginBottom: scale(4),
      },
      historyErrorText: {
        color: theme.palette.error,
        fontSize: scale(12),
        textAlign: 'center',
      },
      historyActions: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: scale(8),
      },
      historyRetry: {
        color: theme.palette.accent700,
        fontSize: scale(12),
        fontWeight: '800',
        paddingVertical: scale(5),
        paddingHorizontal: scale(12),
      },
      loadOlderButton: {
        alignSelf: 'center',
        paddingVertical: scale(8),
        paddingHorizontal: scale(14),
        marginBottom: scale(4),
      },
      loadOlderText: {
        color: theme.palette.accent700,
        fontSize: scale(12),
        fontWeight: '700',
      },
      quickList: {
        flexGrow: 0,
        flexShrink: 0,
        height: scale(56),
      },
      quick: {
        alignItems: 'center',
        gap: scale(7),
        paddingHorizontal: scale(18),
        paddingTop: scale(4),
        paddingBottom: scale(9),
      },
      compose: {
        flexDirection: 'row',
        alignItems: 'flex-end',
        gap: scale(8),
        paddingHorizontal: scale(18),
        paddingTop: scale(8),
        paddingBottom: Math.max(bottomInset, scale(10)),
        borderTopWidth: scale(1),
        borderTopColor: theme.palette.divider,
        backgroundColor: theme.palette.background,
      },
      readOnlyComposer: {
        minHeight: scale(66),
        paddingHorizontal: scale(22),
        paddingVertical: scale(14),
        borderTopWidth: scale(1),
        borderTopColor: theme.palette.divider,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: theme.palette.background,
      },
      readOnlyText: {
        color: theme.palette.neutral600,
        fontSize: scale(12.5),
        lineHeight: scale(18),
        textAlign: 'center',
      },
      input: {
        flex: 1,
        minHeight: scale(44),
        maxHeight: scale(104),
        borderRadius: scale(22),
        backgroundColor: theme.palette.white,
        borderWidth: scale(1),
        borderColor: theme.palette.divider,
        paddingHorizontal: scale(16),
        paddingTop: scale(11),
        paddingBottom: scale(10),
        color: theme.palette.text,
        fontSize: scale(14),
        lineHeight: scale(20),
      },
      send: {
        width: scale(44),
        height: scale(44),
        borderRadius: scale(999),
        backgroundColor: theme.palette.accent,
        alignItems: 'center',
        justifyContent: 'center',
      },
      sendDisabled: { backgroundColor: theme.palette.neutral400 },
      sendPressed: { opacity: 0.72 },
      sendText: {
        color: theme.palette.background,
        fontSize: scale(24),
        lineHeight: scale(27),
        fontWeight: '800',
      },
      headerRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(4),
      },
      menuButton: {
        width: scale(40),
        height: scale(40),
        borderRadius: scale(999),
        alignItems: 'center',
        justifyContent: 'center',
      },
      menuButtonPressed: { backgroundColor: theme.palette.neutral200 },
      menu: {
        position: 'absolute',
        right: scale(18),
        width: scale(236),
        paddingHorizontal: scale(14),
        borderRadius: scale(18),
        borderWidth: scale(1),
        borderColor: theme.palette.divider,
        backgroundColor: theme.palette.white,
        shadowColor: '#000',
        shadowOpacity: 0.14,
        shadowRadius: scale(16),
        shadowOffset: { width: 0, height: scale(6) },
        elevation: 8,
      },
    }),
    colors: {
      placeholder: theme.palette.neutral500,
      menuIcon: theme.palette.text,
    },
    menuIconSize: scale(22),
    menuOffset: scale(4),
    menuHitSlop: scale(6),
    messagesBottomBase: scale(12),
  }),
);
