import { StyleSheet } from 'react-native';
import { createStyles } from 'shared/theme/createStyles';

export const useStyles = createStyles(({ theme, scale }: any) => {
  const shadow = {
    shadowColor: theme.palette.text,
    shadowOffset: { width: 0, height: scale(2) },
    shadowOpacity: 0.08,
    shadowRadius: scale(5),
    elevation: scale(2),
  };

  return {
    ...StyleSheet.create({
      button: {
        height: scale(52),
        borderRadius: scale(999),
        backgroundColor: theme.palette.accent,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: scale(9),
      },
      secondaryButton: {
        height: scale(48),
        backgroundColor: theme.palette.background,
        borderWidth: scale(1),
        borderColor: theme.palette.divider,
      },
      dangerButton: {
        backgroundColor: theme.palette.error,
      },
      disabled: { opacity: 0.5 },
      pressed: { opacity: 0.7 },
      buttonText: {
        fontSize: scale(15),
        fontWeight: '800',
        color: theme.palette.background,
      },
      secondaryButtonText: { color: theme.palette.text },
      dangerButtonText: { color: theme.palette.white },
      chip: {
        minHeight: scale(40),
        borderRadius: scale(999),
        borderWidth: scale(1),
        borderColor: theme.palette.divider,
        paddingHorizontal: scale(14),
        alignItems: 'center',
        justifyContent: 'center',
      },
      chipActive: {
        backgroundColor: theme.palette.accent,
        borderColor: theme.palette.accent,
      },
      chipText: {
        fontSize: scale(12.5),
        fontWeight: '700',
        color: theme.palette.neutral700,
      },
      chipTextActive: { color: theme.palette.background },
      field: { gap: scale(7), marginTop: scale(5) },
      label: {
        fontSize: scale(12),
        fontWeight: '700',
        color: theme.palette.neutral700,
      },
      input: {
        minHeight: scale(48),
        borderRadius: scale(999),
        backgroundColor: theme.palette.white,
        borderWidth: scale(1),
        borderColor: theme.palette.divider,
        paddingHorizontal: scale(16),
        fontSize: scale(14),
        color: theme.palette.text,
      },
      compactInput: { minHeight: scale(44) },
      price: {
        backgroundColor: theme.palette.accent200,
        borderRadius: scale(999),
        paddingVertical: scale(5),
        paddingHorizontal: scale(9),
      },
      free: { backgroundColor: theme.palette.violet200 },
      priceText: {
        fontSize: scale(11.5),
        fontWeight: '800',
        color: theme.palette.accent800,
      },
      freeText: { color: theme.palette.violet800 },
      cover: {
        width: scale(62),
        height: scale(86),
        borderRadius: scale(12),
        padding: scale(9),
        justifyContent: 'flex-end',
        overflow: 'hidden',
      },
      coverAccent: { backgroundColor: theme.palette.accent300 },
      coverViolet: { backgroundColor: theme.palette.violet300 },
      coverNeutral: { backgroundColor: theme.palette.neutral300 },
      coverImage: {
        position: 'absolute',
        top: scale(0),
        right: scale(0),
        bottom: scale(0),
        left: scale(0),
      },
      coverBig: {
        width: scale(168),
        height: scale(232),
        borderRadius: scale(22),
        padding: scale(20),
      },
      coverText: { fontWeight: '800', fontSize: scale(15) },
      coverTextAccent: { color: theme.palette.accent800 },
      coverTextViolet: { color: theme.palette.violet800 },
      coverTextNeutral: { color: theme.palette.neutral800 },
      row: {
        minHeight: scale(110),
        backgroundColor: theme.palette.white,
        borderRadius: scale(28),
        padding: scale(12),
        flexDirection: 'row',
        gap: scale(14),
        alignItems: 'center',
        ...shadow,
      },
      grow: { flex: 1, gap: scale(5) },
      title: {
        fontSize: scale(16),
        lineHeight: scale(19),
        fontWeight: '800',
        color: theme.palette.text,
      },
      meta: { fontSize: scale(12.5), color: theme.palette.neutral600 },
      mini: { fontSize: scale(11.5), color: theme.palette.neutral600 },
      inline: { flexDirection: 'row', alignItems: 'center', gap: scale(8) },
      heart: {
        width: scale(44),
        height: scale(44),
        alignItems: 'center',
        justifyContent: 'center',
      },
      heading: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: theme.palette.neutral200,
      },
      screenHeader: {
        paddingHorizontal: scale(18),
        paddingTop: scale(12),
        paddingBottom: scale(12),
        backgroundColor: theme.palette.background,
        borderBottomWidth: scale(1),
        borderBottomColor: theme.palette.divider,
      },
      screenHeaderRow: {
        flexDirection: 'row',
        alignItems: 'center',
      },
      screenHeaderContent: {
        flex: 1,
      },
      screenHeaderBack: {
        width: scale(44),
        height: scale(44),
        marginLeft: scale(-8),
        marginRight: scale(4),
        alignItems: 'center',
        justifyContent: 'center',
      },
      h2: {
        fontSize: scale(26),
        lineHeight: scale(30),
        fontWeight: '800',
        letterSpacing: scale(-0.6),
        color: theme.palette.text,
      },
      empty: {
        alignItems: 'center',
        paddingVertical: scale(58),
        paddingHorizontal: scale(24),
        gap: scale(13),
      },
      emptyIcon: {
        width: scale(56),
        height: scale(56),
        borderRadius: scale(999),
        backgroundColor: theme.palette.accent200,
        alignItems: 'center',
        justifyContent: 'center',
      },
      emptyText: {
        fontSize: scale(14),
        textAlign: 'center',
        color: theme.palette.neutral600,
        lineHeight: scale(21),
      },
      page: {
        paddingHorizontal: scale(18),
        paddingTop: scale(12),
        paddingBottom: scale(30),
        gap: scale(13),
      },
      subtitle: {
        fontSize: scale(15),
        lineHeight: scale(23),
        color: theme.palette.subtitle,
      },
      back: {
        color: theme.palette.accent700,
        fontSize: scale(15),
        fontWeight: '700',
        paddingVertical: scale(8),
      },
      body: {
        fontSize: scale(14.5),
        lineHeight: scale(22),
        color: theme.palette.text,
      },
    }),
    colors: {
      placeholder: theme.palette.neutral500,
      backIcon: theme.palette.accent700,
      heartIdle: theme.palette.neutral400,
      heartActive: theme.palette.accent,
    },
    iconSizes: { back: scale(30), heart: scale(26), emptyHeart: scale(26) },
    hitSlop: scale(8),
  };
});
